### ISSUE TITLE
llvm::BasicBlock* JumpTargetManager::getBlockAt(uint64_t): Assertion `TargetIt != JumpTargets.end()' failed

### ISSUE THREAD

**Issue by mr-tz** [revng/revamb#3]
Getting this error when trying to translate this file: http://wikisend.com/download/428620/libvalidate.so
```
$ ./translate libvalidate.so
JumpTargets found in global data: 42
revamb: /home/revng/orchestra/revamb/jumptargetmanager.cpp:1113: llvm::BasicBlock* JumpTargetManager::getBlockAt(uint64_t): Assertion `TargetIt != JumpTargets.end()' failed.
```

**Comment by aleclearmind** [comment]
Hi, at this stage we only support statically linked binaries.
Support for dynamic libraries/programs is under development. Please stay tuned.

**Comment by mr-tz** [comment]
Gotcha, thanks!
Looking forward to see where you're going with this project!
