### ISSUE TITLE
Segfault using Docker image or tarball

### ISSUE THREAD

**Issue by bdemick** [revng/revamb#8]
Pulled Docker image and copied a file into the container via a host folder to run analysis of a test binary, and I'm getting a segfault:

> revng@c44edcb16231:~/orchestra$ translate simpleArray3
>revamb: /home/revng/orchestra/revamb/binaryfile.cpp:459: void BinaryFile::parseEHFrame(uint64_t, llvm::Optional<long unsigned int>, llvm::Optional<long unsigned int>) [with T = llvm::object::ELFType<(llvm::support::endianness)1u, true>; uint64_t = long unsigned int]: Assertion `Version == 1' failed.
llvm-link: simpleArray3.ll: error: Could not open input file: No such file or directory
#0 0x00007fc8c541ff28 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/home/revng/orchestra/root/bin/../lib/libLLVMSupport.so+0x11bf28)
#1 0x00007fc8c541e1b6 llvm::sys::RunSignalHandlers() (/home/revng/orchestra/root/bin/../lib/libLLVMSupport.so+0x11a1b6)
#2 0x00007fc8c541e319 (/home/revng/orchestra/root/bin/../lib/libLLVMSupport.so+0x11a319)
#3 0x00007fc8c4f704b0 (/lib/x86_64-linux-gnu/libc.so.6+0x354b0)
#4 0x00007fc8c5f6cbb4 llvm::Module::materializeMetadata() (/home/revng/orchestra/root/bin/../lib/libLLVMCore.so+0x1d3bb4)
#5 0x0000000000404a29 _init (/home/revng/orchestra/root/bin/llvm-link+0x404a29)
#6 0x00000000004052ff _init (/home/revng/orchestra/root/bin/llvm-link+0x4052ff)
#7 0x0000000000403301 _init (/home/revng/orchestra/root/bin/llvm-link+0x403301)
#8 0x00007fc8c4f5b830 __libc_start_main /build/glibc-9tT8Do/glibc-2.23/csu/../csu/libc-start.c:325:0
#9 0x0000000000404379 _init (/home/revng/orchestra/root/bin/llvm-link+0x404379)
Stack dump:
0.	Program arguments: llvm-link simpleArray3.ll /home/revng/orchestra/root/bin/../share/revamb/support-x86_64-normal.ll -o simpleArray3.linked.ll -S
/home/revng/orchestra/root/bin/translate: line 116:    38 Segmentation fault      "$LINK" "$LL" "$SUPPORT_PATH" -o "$LINKED_LL" -S
revng@c44edcb16231:~/orchestra$ echo $LINK

The log indicates there is possibly some issue with parsing the target file that doesn't fail nicely and continues to try to link, but I am unsure exactly how to best troubleshoot. I can supply the binary file if necessary. This also occurs when using the binary tarball distribution on an Ubuntu 17.10 VM. Log file output:

>revng@c44edcb16231:~/orchestra$ cat simpleArray3.ll.log
revamb: /home/revng/orchestra/revamb/binaryfile.cpp:459: void BinaryFile::parseEHFrame(uint64_t, llvm::Optional<long unsigned int>, llvm::Optional<long unsigned int>) [with T = llvm::object::ELFType<(llvm::support::endianness)1u, true>; uint64_t = long unsigned int]: Assertion `Version == 1' failed.

**Comment by aleclearmind** [comment]
Can you please attach the offending program? What compiler, compiler version and architecture are you using? Looks like we met an unexpected version for the `.ehframe` data structure.

Consider that the docker release and the tarball are rather old, we're working on a new, smoother install process.

**Comment by bdemick** [comment]
Attached. It's x64, looks like based on the strings it was compiled with clang-3.6 although I also see references to GCC 4.8.4. and 4.8.2 which seems a little strange. I'm more interested in studying the bitcode produced for this file, so if you have suggestions for a better-supported compiler I can give that a shot.

[simpleArray3.tar.gz](https://github.com/revng/revamb/files/1883988/simpleArray3.tar.gz)

**Comment by aleclearmind** [comment]
Have you tried the [demo](https://rev.ng/download.html). You can also use the program compiled during tests (check out the build directory). You can also check out the [GeneratedIRReference.rst](https://github.com/revng/revamb/blob/master/docs/GeneratedIRReference.rst).

I see your binary is dynamically linked, and has not been compiled with the toolchain we distribute and probably contains floating point instructions, which are not currently supported on x86-64 in the public version. Check out the [limitations](https://polimicg.org/gitlab/revng/revamb/wikis/limitations).

Please consider that many limitations have been solved, we will soon release a version fixing them. In the meantime, please stick to the supported toolchains. I'm closing this issue, feel free to [get in touch directly](https://rev.ng/about.html), we're always curious about the use cases for rev.ng.
