### ISSUE TITLE
Is there more specific step to build?

### ISSUE THREAD

**Issue by chlizheng** [revng/revamb#9]
Hi.
I want to try to use this project to translate arm assembly or binary code to llvm-ir. But I 'm a new hand. I can't build a project just according to the README file. Even when I run " cmake .." it failed.  Is I also should iinstall QEMU and GNU toolchain and is there some restriction for version? So, is there more specific step to build it?
best regards

**Comment by aleclearmind** [comment]
Hi, please use [orchestra](https://github.com/revng/orchestra), it will do everything for you!
Please consider the fact that the public repository on GitHub are quite outdated, feel free to [get in touch](https://rev.ng/about.html) with us and tell us about your use case, so we can give you access to our internal repos.

We will eventually update the public ones.
